name: Update Naukri Profile

on:
  schedule:
    - cron: "*/40  * * * *"  # Runs every 40 minutes
  workflow_dispatch: 

permissions:
  contents: read
# env:
#   # Opt into Node.js 24 for the runner environment now
#   FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update_naukri:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Install Playwright Browsers
        run: npx playwright install
      - name: Check Playwright Installation
        run: npx playwright --version
      - name: "Decoder"
        shell: pwsh
        run: |
          .\decoder.ps1
          
      - name: Run Naukri agent
        run: node agent.js
        env:
          NAUKRI_USER: ${{ secrets.NAUKRI_USER }}
          NAUKRI_PASS: ${{ secrets.NAUKRI_PASS }}
      - name: "List directory"
        shell: pwsh
        run: |
          dir
        if: ${{ always() }}
      - name: Upload Screenshots
        uses: actions/upload-artifact@v7.0.1
        if: ${{ always() }}
        with:
          name: Naukri-screensots
          path: |
            **/*.png
            

         
          
        
